name: Build and Publish

on:
  push:
    branches:
      - main
    paths:
      - "packages/client-js/**"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./packages/client-js/package-lock.json
          registry-url: "https://registry.npmjs.org"
      - run: npm install
        working-directory: ./packages/client-js
      - run: npm run build
        working-directory: ./packages/client-js
      - run: npm version patch -m "Bump version to %s [skip ci]" --git-tag-version false
        working-directory: ./packages/client-js
      - run: npm publish --access public
        working-directory: ./packages/client-js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump version [skip ci]"
