name: Build and Publish Python

on:
  push:
    branches:
      - main
    paths:
      - "packages/client-py/**"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          # NB: we use pyproject.toml so we can straight use the build command
      - run: python3 -m pip install --upgrade build twine bump-my-version
        working-directory: ./packages/client-py
      - name: Bump version
        run: bump-my-version bump patch
        working-directory: ./packages/client-py
      - run: python3 -m build
        working-directory: ./packages/client-py
      - run: python3 -m twine upload --repository pypi dist/*
        working-directory: ./packages/client-py
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump version [skip ci]"
